version: "3.9"

services:
  app:
    image: minchae3618/django-mc:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wanted
      - POSTGRES_PASSWORD=wanted
      - POSTGRES_DB=wanted
    restart: always

volumes:
  dev-db-data:
